/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wade3
 */
public class frmdashboard extends javax.swing.JFrame {

    /**
     * Creates new form frmdashboard
     */
    public frmdashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlside = new javax.swing.JPanel();
        lbldashboard = new javax.swing.JLabel();
        lblinventory = new javax.swing.JLabel();
        lblsalesproccesing = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        pnltodayssales = new javax.swing.JPanel();
        lbltodayssales = new javax.swing.JLabel();
        lbltodayssalesnum = new javax.swing.JLabel();
        pnltotalproducts = new javax.swing.JPanel();
        lbltotalproducts = new javax.swing.JLabel();
        lbltotalproductsnum = new javax.swing.JLabel();
        pnllowstockalert = new javax.swing.JPanel();
        lbllowstockalert = new javax.swing.JLabel();
        lbllowstockalertsnum = new javax.swing.JLabel();
        pnlrecenttransactions = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblrecenttransactions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashbord");
        setResizable(false);

        pnlside.setBackground(new java.awt.Color(0, 0, 0));

        lbldashboard.setBackground(new java.awt.Color(0, 0, 0));
        lbldashboard.setForeground(new java.awt.Color(240, 240, 240));
        lbldashboard.setText("Dashboard");

        lblinventory.setBackground(new java.awt.Color(0, 0, 0));
        lblinventory.setForeground(new java.awt.Color(240, 240, 240));
        lblinventory.setText("Inventory");

        lblsalesproccesing.setBackground(new java.awt.Color(0, 0, 0));
        lblsalesproccesing.setForeground(new java.awt.Color(240, 240, 240));
        lblsalesproccesing.setText("Sales Processing");

        lbllogout.setBackground(new java.awt.Color(0, 0, 0));
        lbllogout.setForeground(new java.awt.Color(240, 240, 240));
        lbllogout.setText("Logout");

        javax.swing.GroupLayout pnlsideLayout = new javax.swing.GroupLayout(pnlside);
        pnlside.setLayout(pnlsideLayout);
        pnlsideLayout.setHorizontalGroup(
            pnlsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldashboard)
                    .addComponent(lblinventory)
                    .addComponent(lblsalesproccesing)
                    .addComponent(lbllogout))
                .addGap(56, 56, 56))
        );
        pnlsideLayout.setVerticalGroup(
            pnlsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsideLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbldashboard)
                .addGap(36, 36, 36)
                .addComponent(lblinventory)
                .addGap(34, 34, 34)
                .addComponent(lblsalesproccesing)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbllogout)
                .addContainerGap())
        );

        pnltodayssales.setBackground(new java.awt.Color(204, 204, 204));
        pnltodayssales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        lbltodayssales.setText("Todays Sales");

        lbltodayssalesnum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltodayssalesnum.setText("1450$");

        javax.swing.GroupLayout pnltodayssalesLayout = new javax.swing.GroupLayout(pnltodayssales);
        pnltodayssales.setLayout(pnltodayssalesLayout);
        pnltodayssalesLayout.setHorizontalGroup(
            pnltodayssalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltodayssalesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnltodayssalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltodayssales)
                    .addGroup(pnltodayssalesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbltodayssalesnum)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnltodayssalesLayout.setVerticalGroup(
            pnltodayssalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltodayssalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltodayssales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltodayssalesnum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnltotalproducts.setBackground(new java.awt.Color(204, 204, 204));
        pnltotalproducts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        lbltotalproducts.setText("Total Products");

        lbltotalproductsnum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltotalproductsnum.setText("128");

        javax.swing.GroupLayout pnltotalproductsLayout = new javax.swing.GroupLayout(pnltotalproducts);
        pnltotalproducts.setLayout(pnltotalproductsLayout);
        pnltotalproductsLayout.setHorizontalGroup(
            pnltotalproductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltotalproductsLayout.createSequentialGroup()
                .addGroup(pnltotalproductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnltotalproductsLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbltotalproducts))
                    .addGroup(pnltotalproductsLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lbltotalproductsnum)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnltotalproductsLayout.setVerticalGroup(
            pnltotalproductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltotalproductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltotalproducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltotalproductsnum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnllowstockalert.setBackground(new java.awt.Color(204, 204, 204));
        pnllowstockalert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        lbllowstockalert.setText("Low Stock Alert");

        lbllowstockalertsnum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbllowstockalertsnum.setText("3");

        javax.swing.GroupLayout pnllowstockalertLayout = new javax.swing.GroupLayout(pnllowstockalert);
        pnllowstockalert.setLayout(pnllowstockalertLayout);
        pnllowstockalertLayout.setHorizontalGroup(
            pnllowstockalertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnllowstockalertLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(lbllowstockalert)
                .addGap(29, 29, 29))
            .addGroup(pnllowstockalertLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lbllowstockalertsnum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnllowstockalertLayout.setVerticalGroup(
            pnllowstockalertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllowstockalertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbllowstockalert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbllowstockalertsnum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlrecenttransactions.setBackground(new java.awt.Color(204, 204, 204));
        pnlrecenttransactions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlrecenttransactions.setForeground(new java.awt.Color(255, 255, 255));
        pnlrecenttransactions.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Mechanical Gaming Keyboard---120$---Completed");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("RTX 4090 GPU---1600$---Completed");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Wireless Mouse---50$---Completed");

        lblrecenttransactions.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblrecenttransactions.setText("Recent Transactions");

        javax.swing.GroupLayout pnlrecenttransactionsLayout = new javax.swing.GroupLayout(pnlrecenttransactions);
        pnlrecenttransactions.setLayout(pnlrecenttransactionsLayout);
        pnlrecenttransactionsLayout.setHorizontalGroup(
            pnlrecenttransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrecenttransactionsLayout.createSequentialGroup()
                .addGroup(pnlrecenttransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlrecenttransactionsLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lblrecenttransactions))
                    .addGroup(pnlrecenttransactionsLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnlrecenttransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        pnlrecenttransactionsLayout.setVerticalGroup(
            pnlrecenttransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlrecenttransactionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblrecenttransactions)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(pnltodayssales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(pnltotalproducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(pnllowstockalert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnlrecenttransactions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnltodayssales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnltotalproducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnllowstockalert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addComponent(pnlrecenttransactions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmdashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmdashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbldashboard;
    private javax.swing.JLabel lblinventory;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lbllowstockalert;
    private javax.swing.JLabel lbllowstockalertsnum;
    private javax.swing.JLabel lblrecenttransactions;
    private javax.swing.JLabel lblsalesproccesing;
    private javax.swing.JLabel lbltodayssales;
    private javax.swing.JLabel lbltodayssalesnum;
    private javax.swing.JLabel lbltotalproducts;
    private javax.swing.JLabel lbltotalproductsnum;
    private javax.swing.JPanel pnllowstockalert;
    private javax.swing.JPanel pnlrecenttransactions;
    private javax.swing.JPanel pnlside;
    private javax.swing.JPanel pnltodayssales;
    private javax.swing.JPanel pnltotalproducts;
    // End of variables declaration//GEN-END:variables
}
