/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wade3
 */
public class frminventory extends javax.swing.JFrame {

    /**
     * Creates new form frminventory
     */
    public frminventory() {
        initComponents();
        setupNavigationAndActions();
        syncWithDashboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlside = new javax.swing.JPanel();
        lbldashboard = new javax.swing.JLabel();
        lblinventory = new javax.swing.JLabel();
        lblsalesproccesing = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblprice = new javax.swing.JLabel();
        lblstockquantity = new javax.swing.JLabel();
        lblproductname = new javax.swing.JLabel();
        lblcategory = new javax.swing.JLabel();
        lblactions = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblthestockquantity = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblthecategory = new javax.swing.JLabel();
        lbltheproductname = new javax.swing.JLabel();
        lbltheprice = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblthestockquantity1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblthecategory1 = new javax.swing.JLabel();
        lbltheproductname1 = new javax.swing.JLabel();
        lbltheprice1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory");
        setResizable(false);

        pnlside.setBackground(new java.awt.Color(0, 0, 0));

        lbldashboard.setBackground(new java.awt.Color(0, 0, 0));
        lbldashboard.setForeground(new java.awt.Color(240, 240, 240));
        lbldashboard.setText("Dashboard");

        lblinventory.setBackground(new java.awt.Color(0, 0, 0));
        lblinventory.setForeground(new java.awt.Color(240, 240, 240));
        lblinventory.setText("Inventory");

        lblsalesproccesing.setBackground(new java.awt.Color(0, 0, 0));
        lblsalesproccesing.setForeground(new java.awt.Color(240, 240, 240));
        lblsalesproccesing.setText("Sales Processing");

        lbllogout.setBackground(new java.awt.Color(0, 0, 0));
        lbllogout.setForeground(new java.awt.Color(240, 240, 240));
        lbllogout.setText("Logout");

        javax.swing.GroupLayout pnlsideLayout = new javax.swing.GroupLayout(pnlside);
        pnlside.setLayout(pnlsideLayout);
        pnlsideLayout.setHorizontalGroup(
            pnlsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldashboard)
                    .addComponent(lblinventory)
                    .addComponent(lblsalesproccesing)
                    .addComponent(lbllogout))
                .addGap(56, 56, 56))
        );
        pnlsideLayout.setVerticalGroup(
            pnlsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsideLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbldashboard)
                .addGap(36, 36, 36)
                .addComponent(lblinventory)
                .addGap(34, 34, 34)
                .addComponent(lblsalesproccesing)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(lbllogout)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lblprice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblprice.setForeground(new java.awt.Color(255, 255, 255));
        lblprice.setText("Price");

        lblstockquantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblstockquantity.setForeground(new java.awt.Color(255, 255, 255));
        lblstockquantity.setText("Stock Quantity");

        lblproductname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblproductname.setForeground(new java.awt.Color(255, 255, 255));
        lblproductname.setText("Product Name");

        lblcategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcategory.setForeground(new java.awt.Color(255, 255, 255));
        lblcategory.setText("Category");

        lblactions.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblactions.setForeground(new java.awt.Color(255, 255, 255));
        lblactions.setText("Actions");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblproductname)
                .addGap(33, 33, 33)
                .addComponent(lblcategory)
                .addGap(37, 37, 37)
                .addComponent(lblprice)
                .addGap(42, 42, 42)
                .addComponent(lblstockquantity)
                .addGap(32, 32, 32)
                .addComponent(lblactions)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblproductname)
                    .addComponent(lblcategory)
                    .addComponent(lblprice)
                    .addComponent(lblstockquantity)
                    .addComponent(lblactions))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblthestockquantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblthestockquantity.setText("25");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Edit / Delete");

        lblthecategory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblthecategory.setText("Peripherals");

        lbltheproductname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbltheproductname.setText("Mecanical Keyboard");

        lbltheprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbltheprice.setText("120$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltheproductname)
                .addGap(18, 18, 18)
                .addComponent(lblthecategory)
                .addGap(39, 39, 39)
                .addComponent(lbltheprice)
                .addGap(73, 73, 73)
                .addComponent(lblthestockquantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltheproductname)
                    .addComponent(lblthecategory)
                    .addComponent(lbltheprice)
                    .addComponent(lblthestockquantity)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblthestockquantity1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblthestockquantity1.setForeground(new java.awt.Color(255, 0, 0));
        lblthestockquantity1.setText("3");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Edit / Delete");

        lblthecategory1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblthecategory1.setText("Components");

        lbltheproductname1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbltheproductname1.setText("RTX 4090 GPU");

        lbltheprice1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbltheprice1.setText("1600$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltheproductname1)
                .addGap(30, 30, 30)
                .addComponent(lblthecategory1)
                .addGap(33, 33, 33)
                .addComponent(lbltheprice1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblthestockquantity1)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltheproductname1)
                    .addComponent(lblthecategory1)
                    .addComponent(lbltheprice1)
                    .addComponent(lblthestockquantity1)
                    .addComponent(jLabel2))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Add New Product");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(63, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String name = javax.swing.JOptionPane.showInputDialog(this, "Enter Product Name:");
        if (name == null || name.trim().isEmpty()) return;

        String category = javax.swing.JOptionPane.showInputDialog(this, "Enter Category:");
        if (category == null || category.trim().isEmpty()) return;

        String priceStr = javax.swing.JOptionPane.showInputDialog(this, "Enter Price ($):");
        if (priceStr == null) return;

        String qtyStr = javax.swing.JOptionPane.showInputDialog(this, "Enter Stock Quantity:");
        if (qtyStr == null) return;

        
        try {
            double price = Double.parseDouble(priceStr);
            int qty = Integer.parseInt(qtyStr);

            if (price < 0 || qty < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Values cannot be negative!", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            
            javax.swing.JOptionPane.showMessageDialog(this, "Product '" + name + "' added successfully!\n(UI rows full, system counters updated).");
            
            frmdashboard.totalProducts += 1;
            if (qty <= 5) frmdashboard.lowStockCount += 1;
            
            syncWithDashboard();

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Format! Price must be a decimal number and Stock must be a whole integer.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frminventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frminventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frminventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frminventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frminventory().setVisible(true);
            }
        });
    }
    
    private void setupNavigationAndActions() {
        lbldashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbldashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frmdashboard db = new frmdashboard();
                db.setVisible(true);
                dispose();
            }
        });

        
        lblsalesproccesing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblsalesproccesing.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frmsalesprocceisng sp = new frmsalesprocceisng();
                sp.setVisible(true);
                dispose();
            }
        });

        
        lbllogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int confirm = javax.swing.JOptionPane.showConfirmDialog(frminventory.this,
                    "Are you sure you want to logout?", "Logout", javax.swing.JOptionPane.YES_NO_OPTION);
                if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                    frmlogin login = new frmlogin();
                    login.setVisible(true);
                    dispose();
                }
            }
        });

        
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleRowAction(lbltheproductname, lbltheprice, lblthestockquantity);
            }
        });

        
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                handleRowAction(lbltheproductname1, lbltheprice1, lblthestockquantity1);
            }
        });
    }

   
    private void handleRowAction(javax.swing.JLabel nameLbl, javax.swing.JLabel priceLbl, javax.swing.JLabel qtyLbl) {
        String[] options = {"Edit Stock/Price", "Delete Product", "Cancel"};
        int choice = javax.swing.JOptionPane.showOptionDialog(this, 
            "What action do you want to perform on " + nameLbl.getText() + "?", 
            "Product Actions", javax.swing.JOptionPane.DEFAULT_OPTION, 
            javax.swing.JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (choice == 0) { 
            String newPrice = javax.swing.JOptionPane.showInputDialog(this, "Enter New Price ($):", priceLbl.getText().replace("$", ""));
            String newQty = javax.swing.JOptionPane.showInputDialog(this, "Enter New Stock Quantity:", qtyLbl.getText());
            
            try {
                double p = Double.parseDouble(newPrice);
                int q = Integer.parseInt(newQty);
                if (p < 0 || q < 0) throw new NumberFormatException();
                
                priceLbl.setText(String.format("%.0f$", p));
                qtyLbl.setText(String.valueOf(q));
                
               
                if (q <= 5) {
                    qtyLbl.setForeground(java.awt.Color.RED);
                } else {
                    qtyLbl.setForeground(java.awt.Color.BLACK);
                }
                
                javax.swing.JOptionPane.showMessageDialog(this, "Product information updated successfully!");
                syncWithDashboard();
                
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid numeric input. Changes discarded.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else if (choice == 1) { 
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to clear this item slot?", "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);
            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                nameLbl.setText("[Empty Slot]");
                priceLbl.setText("0$");
                qtyLbl.setText("0");
                qtyLbl.setForeground(java.awt.Color.GRAY);
                syncWithDashboard();
            }
        }
    }

    private void syncWithDashboard() {
        int activeProducts = 0;
        int lowStockTotal = 0;

        
        if (!lbltheproductname.getText().equals("[Empty Slot]")) {
            activeProducts++;
            int q1 = Integer.parseInt(lblthestockquantity.getText());
            if (q1 <= 5 && q1 > 0) lowStockTotal++;
        }
        
        if (!lbltheproductname1.getText().equals("[Empty Slot]")) {
            activeProducts++;
            int q2 = Integer.parseInt(lblthestockquantity1.getText());
            if (q2 <= 5 && q2 > 0) lowStockTotal++;
        }

        
        if (frmdashboard.totalProducts == 0 && activeProducts > 0) {
            frmdashboard.totalProducts = 128; 
            frmdashboard.lowStockCount = 3;
        } else {
            frmdashboard.totalProducts = activeProducts;
            frmdashboard.lowStockCount = lowStockTotal;
        }
    }
   
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblactions;
    private javax.swing.JLabel lblcategory;
    private javax.swing.JLabel lbldashboard;
    private javax.swing.JLabel lblinventory;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lblproductname;
    private javax.swing.JLabel lblsalesproccesing;
    private javax.swing.JLabel lblstockquantity;
    private javax.swing.JLabel lblthecategory;
    private javax.swing.JLabel lblthecategory1;
    private javax.swing.JLabel lbltheprice;
    private javax.swing.JLabel lbltheprice1;
    private javax.swing.JLabel lbltheproductname;
    private javax.swing.JLabel lbltheproductname1;
    private javax.swing.JLabel lblthestockquantity;
    private javax.swing.JLabel lblthestockquantity1;
    private javax.swing.JPanel pnlside;
    // End of variables declaration                   

   
}
