/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wade3
 */
public class frmsalesprocceisng extends javax.swing.JFrame {

    /**
     * Creates new form frmsalesprocceisng
     */
    public frmsalesprocceisng() {
        initComponents();
        setupSalesEngine();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlside = new javax.swing.JPanel();
        lbldashboard = new javax.swing.JLabel();
        lblinventory = new javax.swing.JLabel();
        lblsalesproccesing = new javax.swing.JLabel();
        lbllogout = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblcart = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        btnfinish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Proccesing");
        setResizable(false);

        pnlside.setBackground(new java.awt.Color(0, 0, 0));

        lbldashboard.setBackground(new java.awt.Color(0, 0, 0));
        lbldashboard.setForeground(new java.awt.Color(240, 240, 240));
        lbldashboard.setText("Dashboard");

        lblinventory.setBackground(new java.awt.Color(0, 0, 0));
        lblinventory.setForeground(new java.awt.Color(240, 240, 240));
        lblinventory.setText("Inventory");

        lblsalesproccesing.setBackground(new java.awt.Color(0, 0, 0));
        lblsalesproccesing.setForeground(new java.awt.Color(240, 240, 240));
        lblsalesproccesing.setText("Sales Processing");

        lbllogout.setBackground(new java.awt.Color(0, 0, 0));
        lbllogout.setForeground(new java.awt.Color(240, 240, 240));
        lbllogout.setText("Logout");

        javax.swing.GroupLayout pnlsideLayout = new javax.swing.GroupLayout(pnlside);
        pnlside.setLayout(pnlsideLayout);
        pnlsideLayout.setHorizontalGroup(
            pnlsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldashboard)
                    .addComponent(lblinventory)
                    .addComponent(lblsalesproccesing)
                    .addComponent(lbllogout))
                .addGap(56, 56, 56))
        );
        pnlsideLayout.setVerticalGroup(
            pnlsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsideLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbldashboard)
                .addGap(36, 36, 36)
                .addComponent(lblinventory)
                .addGap(34, 34, 34)
                .addComponent(lblsalesproccesing)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, Short.MAX_VALUE)
                .addComponent(lbllogout)
                .addContainerGap())
        );

        txtsearch.setBackground(new java.awt.Color(204, 204, 204));
        txtsearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(102, 102, 102));
        txtsearch.setText("Search for products by name...");
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("RTX 4090 GPU-$1600");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Wireless Mouse-$50");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        lblcart.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblcart.setText("Cart");

        lbltotal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbltotal.setText("Total:$1650");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblcart)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lbltotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbltotal)
                .addContainerGap())
        );

        btnfinish.setBackground(new java.awt.Color(51, 153, 255));
        btnfinish.setText("Complete Purchase & Print Receipt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnfinish)
                        .addGap(205, 205, 205))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(560, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnfinish, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String query = txtsearch.getText().toLowerCase().trim();
        if (query.contains("gpu") || query.contains("4090")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Product Found: RTX 4090 GPU\nPrice: $1600\nStatus: In Cart", "Search Result", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else if (query.contains("mouse") || query.contains("wireless")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Product Found: Wireless Mouse\nPrice: $50\nStatus: In Cart", "Search Result", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Product not found in system.", "Search Result", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmsalesprocceisng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmsalesprocceisng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmsalesprocceisng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmsalesprocceisng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmsalesprocceisng().setVisible(true);
            }
        });
    }

    private void setupSalesEngine() {
        txtsearch.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtsearch.getText().equals("Search for products by name...")) {
                    txtsearch.setText("");
                    txtsearch.setForeground(java.awt.Color.BLACK);
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtsearch.getText().isEmpty()) {
                    txtsearch.setText("Search for products by name...");
                    txtsearch.setForeground(new java.awt.Color(102, 102, 102));
                }
            }
        });

        lbldashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbldashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frmdashboard db = new frmdashboard();
                db.setVisible(true);
                dispose();
            }
        });

        lblinventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblinventory.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frminventory inv = new frminventory();
                inv.setVisible(true);
                dispose();
            }
        });

        lbllogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int confirm = javax.swing.JOptionPane.showConfirmDialog(frmsalesprocceisng.this,
                    "Are you sure you want to logout?", "Logout", javax.swing.JOptionPane.YES_NO_OPTION);
                if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                    frmlogin login = new frmlogin();
                    login.setVisible(true);
                    dispose();
                }
            }
        });

        btnfinish.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processCheckout();
            }
        });
    }

    private void processCheckout() {
        if (jLabel1.getText().isEmpty() && jLabel2.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "The checkout cart is currently empty!", "Checkout Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        double totalToCharge = 0.0;
        StringBuilder receiptDetails = new StringBuilder("=== TRANSACTION RECEIPT ===\n\n");

        if (!jLabel1.getText().isEmpty()) {
            frmdashboard.addLiveSale(1600.0, "RTX 4090 GPU");
            totalToCharge += 1600.0;
            receiptDetails.append("- RTX 4090 GPU: $1600.00\n");
        }
        if (!jLabel2.getText().isEmpty()) {
            frmdashboard.addLiveSale(50.0, "Wireless Mouse");
            totalToCharge += 50.0;
            receiptDetails.append("- Wireless Mouse: $50.00\n");
        }

        receiptDetails.append("\n-----------------------------\n");
        receiptDetails.append(String.format("TOTAL PAID: $%.2f\n", totalToCharge));
        receiptDetails.append("=============================\n");
        receiptDetails.append("Payment Processed Successfully!");

        javax.swing.JOptionPane.showMessageDialog(this, receiptDetails.toString(), "Receipt Printer Terminal", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        
        jLabel1.setText("");
        jLabel2.setText("");
        lbltotal.setText("Total: $0.00");
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnfinish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblcart;
    private javax.swing.JLabel lbldashboard;
    private javax.swing.JLabel lblinventory;
    private javax.swing.JLabel lbllogout;
    private javax.swing.JLabel lblsalesproccesing;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JPanel pnlside;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration                   
}
